name: 'Microsoft Teams'
description: 'Send messages to Microsoft Teams'
author: itdesign GmbH
inputs:
  title:
    description: 'Message Title. Does not work with json-content. Provide it ihn the JSON Object.'
    required: false
  color:
    description: 'Message Color. Does not work with json-content. Provide it ihn the JSON Object.'
    required: false
  body:
    description: 'Message Body. Either json-content or body must be provided.'
    required: false
  json-content:
    description: 'The json content of the Teams message. Either json-content or body must be provided.'
  webhook:
    description: 'Microsoft Teams Webhook URL'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'message-square'
  color: 'purple'
