on: workflow_dispatch

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send test message
        uses: ./
        with:
          color: '#01A6F0'
          body: |
            Test
            # multiline 🦙
          webhook: ${{ secrets.WEBHOOK_URL }}
